apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: savbl7z0a-python 
  janus-idp.io/tekton: savbl7z0a-python
  backstage.io/kubernetes-id: savbl7z0a-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: savbl7z0a-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml